"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const deviceController_1 = require("../controllers/deviceController");
const router = (0, express_1.Router)();
router.get('/', deviceController_1.getAllDevices);
router.get('/online', deviceController_1.getOnlineDevices);
router.get('/printers/all', deviceController_1.getAllDevicePrinters);
router.get('/type/:type', deviceController_1.getDevicesByType);
router.get('/:id', deviceController_1.getDeviceById);
router.get('/device-id/:deviceId', deviceController_1.getDeviceByDeviceId);
router.post('/', deviceController_1.createDevice);
router.post('/register', deviceController_1.createDevice);
router.put('/:id', deviceController_1.updateDevice);
router.patch('/:deviceId/status', deviceController_1.updateDeviceStatus);
router.delete('/:id', deviceController_1.deleteDevice);
router.get('/:deviceId/printers', deviceController_1.getDevicePrintersByDevice);
router.post('/:deviceId/printers', deviceController_1.createDevicePrinter);
router.put('/printers/:id', deviceController_1.updateDevicePrinter);
router.delete('/printers/:id', deviceController_1.deleteDevicePrinter);
exports.default = router;
