"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const serviceController_1 = require("../controllers/serviceController");
const router = (0, express_1.Router)();
router.get('/', serviceController_1.getAllServices);
router.get('/:id', serviceController_1.getServiceById);
router.post('/', serviceController_1.createService);
router.put('/:id', serviceController_1.updateService);
router.delete('/:id', serviceController_1.deleteService);
exports.default = router;
