"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.handleAdminEvents = exports.cleanupStaleDevices = exports.getConnectedDevices = exports.handleDeviceEvents = exports.handleTicketEvents = exports.socketConfig = exports.DEVICE_TYPES = exports.SOCKET_ROOMS = exports.SOCKET_EVENTS = exports.setupSocketHandlers = exports.closeSocket = exports.getConnectionStats = exports.broadcastToAll = exports.emitToDevice = exports.emitToRoom = exports.emitToAll = exports.getSocketIO = exports.initializeSocket = void 0;
var socket_instance_1 = require("./socket.instance");
Object.defineProperty(exports, "initializeSocket", { enumerable: true, get: function () { return socket_instance_1.initializeSocket; } });
Object.defineProperty(exports, "getSocketIO", { enumerable: true, get: function () { return socket_instance_1.getSocketIO; } });
Object.defineProperty(exports, "emitToAll", { enumerable: true, get: function () { return socket_instance_1.emitToAll; } });
Object.defineProperty(exports, "emitToRoom", { enumerable: true, get: function () { return socket_instance_1.emitToRoom; } });
Object.defineProperty(exports, "emitToDevice", { enumerable: true, get: function () { return socket_instance_1.emitToDevice; } });
Object.defineProperty(exports, "broadcastToAll", { enumerable: true, get: function () { return socket_instance_1.broadcastToAll; } });
Object.defineProperty(exports, "getConnectionStats", { enumerable: true, get: function () { return socket_instance_1.getConnectionStats; } });
Object.defineProperty(exports, "closeSocket", { enumerable: true, get: function () { return socket_instance_1.closeSocket; } });
var socket_handler_1 = require("./socket.handler");
Object.defineProperty(exports, "setupSocketHandlers", { enumerable: true, get: function () { return socket_handler_1.setupSocketHandlers; } });
var socket_config_1 = require("./socket.config");
Object.defineProperty(exports, "SOCKET_EVENTS", { enumerable: true, get: function () { return socket_config_1.SOCKET_EVENTS; } });
Object.defineProperty(exports, "SOCKET_ROOMS", { enumerable: true, get: function () { return socket_config_1.SOCKET_ROOMS; } });
Object.defineProperty(exports, "DEVICE_TYPES", { enumerable: true, get: function () { return socket_config_1.DEVICE_TYPES; } });
Object.defineProperty(exports, "socketConfig", { enumerable: true, get: function () { return socket_config_1.socketConfig; } });
var ticket_handler_1 = require("./handlers/ticket.handler");
Object.defineProperty(exports, "handleTicketEvents", { enumerable: true, get: function () { return ticket_handler_1.handleTicketEvents; } });
var device_handler_1 = require("./handlers/device.handler");
Object.defineProperty(exports, "handleDeviceEvents", { enumerable: true, get: function () { return device_handler_1.handleDeviceEvents; } });
Object.defineProperty(exports, "getConnectedDevices", { enumerable: true, get: function () { return device_handler_1.getConnectedDevices; } });
Object.defineProperty(exports, "cleanupStaleDevices", { enumerable: true, get: function () { return device_handler_1.cleanupStaleDevices; } });
var admin_handler_1 = require("./handlers/admin.handler");
Object.defineProperty(exports, "handleAdminEvents", { enumerable: true, get: function () { return admin_handler_1.handleAdminEvents; } });
