"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.closeDatabase = exports.getDatabase = exports.initializeDatabase = exports.systemOperations = exports.devicePrinterOperations = exports.deviceOperations = exports.windowOperations = exports.ticketOperations = exports.serviceOperations = void 0;
var services_1 = require("./services");
Object.defineProperty(exports, "serviceOperations", { enumerable: true, get: function () { return services_1.serviceOperations; } });
var tickets_1 = require("./tickets");
Object.defineProperty(exports, "ticketOperations", { enumerable: true, get: function () { return tickets_1.ticketOperations; } });
var windows_1 = require("./windows");
Object.defineProperty(exports, "windowOperations", { enumerable: true, get: function () { return windows_1.windowOperations; } });
var device_operations_1 = require("./device.operations");
Object.defineProperty(exports, "deviceOperations", { enumerable: true, get: function () { return device_operations_1.deviceOperations; } });
Object.defineProperty(exports, "devicePrinterOperations", { enumerable: true, get: function () { return device_operations_1.devicePrinterOperations; } });
var system_operations_1 = require("./system.operations");
Object.defineProperty(exports, "systemOperations", { enumerable: true, get: function () { return system_operations_1.systemOperations; } });
var connection_1 = require("../connection");
Object.defineProperty(exports, "initializeDatabase", { enumerable: true, get: function () { return connection_1.initializeConnection; } });
Object.defineProperty(exports, "getDatabase", { enumerable: true, get: function () { return connection_1.getDatabase; } });
Object.defineProperty(exports, "closeDatabase", { enumerable: true, get: function () { return connection_1.closeConnection; } });
